### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by afoninsky** [prune998/certmerge-operator#5]
Hello.

As I can see, your pull-request according to labels is not accepted. Is it possible to use existing seret labels generated by certmanager in CertMerge label selector? Ex.:
```
  - labelselector:
      matchExpressions:
        - key: certmanager.k8s.io/certificate-name
          operator: NotIn
          values:
            - non-existing
```

Something like `k get secret --all-namespaces -l certmanager.k8s.io/certificate-name`
